[package]
name = "handlr"
version = "0.3.1"
authors = ["greg <gregory.mkv@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Manage mimeapps.list and default applications with ease"

[dependencies]
pest = "2.1.3"
pest_derive = "2.1.0"
structopt = "0.3.14"
url = "2.1.1"
itertools = "0.9.0"
json = "0.12.4"
shlex = "0.1.1"
thiserror = "1.0.18"
ascii_table = "3.0.0"
mime-db = "0.1.5"
mime-sniffer = "0.1.2"
xdg = "2.2.0"

[profile.release]
opt-level=3
lto=true
