[package]
name = "mime"
version = "0.1.0"
authors = ["greg <gregory.mkv@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "2.0.2"
anyhow = "1.0.28"
pest = "2.1.3"
pest_derive = "2.1.0"
rayon = "1.3.0"
dashmap = "3.10.0"
structopt = "0.3.12"
url = "2.1.1"
mime_guess = "2.0.3"
itertools = "0.9.0"
derive_more = {version = "0.99.5", default-features = false, features = ["display"] }
