[workspace]
resolver = "2"
members = [
  "handlr-regex",
  "xtask"
]
default-members = [
  "handlr-regex"
]

[profile.release]
opt-level = "z"
lto = true
strip = true
codegen-units = 1
panic = "abort"

