[package]
name = "handlr"
version = "0.1.0"
authors = ["greg <gregory.mkv@gmail.com>"]
edition = "2018"

[dependencies]
dirs = "2.0.2"
pest = "2.1.3"
pest_derive = "2.1.0"
rayon = "1.3.0"
dashmap = "3.10.0"
structopt = "0.3.12"
url = "2.1.1"
mime_guess = "2.0.3"
itertools = "0.9.0"
derive_more = {version = "0.99.5", default-features = false, features = ["display"] }
json = "0.12.4"
shlex = "0.1.1"
thiserror = "1.0.14"
ascii_table = "3.0.0"
mime-db = "0.1.5"
